replica:
  replicaCount: 1

auth:
  enabled: true
  password: "p4ss@v1rt"

metrics:
  ## Se desejar que as metricas sejam expostas para uso no prometheus set true
  enabled: false
   
service:
  
  type: ClusterIP 
  port: 6379
  