{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "guestbook.serviceAccountName" . }}
  labels:
{{ include "guestbook.labels" . | indent 4 }}
{{- end -}}

